refactor NearLimitRatio to environment variable
envoyproxy/ratelimit pull request #186
Opened 2020-11-02 04:30 UTC by zufardhiyaulhaq

Issue: https://github.com/envoyproxy/ratelimit/issues/159

According to this issue, I am moving NearLimitRatio constant 0.8 to a configurable environment variable with default is 0.8

2020-11-02 11:16 UTC, zufardhiyaulhaq commented
/retest

2020-11-02 16:05 UTC, mattklein123 commented
Please check CI and also add documentation to README.md. Otherwise LGTM!

2020-11-02 17:14 UTC, zufardhiyaulhaq commented
@mattklein123 I am not sure that this test fails because of my changes
```
--- FAIL: TestBasicAuthConfigWithRedisCluster (4.35s)
    --- FAIL: TestBasicAuthConfigWithRedisCluster/WithoutPerSecondRedisAuthWithLocalCache (1.09s)
        common.go:77: 
            	Error Trace:	common.go:77
            	            				integration_test.go:406
            	Error:      	Should be true
            	Test:       	TestBasicAuthConfigWithRedisCluster/WithoutPerSecondRedisAuthWithLocalCache
            	Messages:   	These two protobuf messages are not equal:
            	            	expected: overall_code:OK  statuses:{code:OK  current_limit:{requests_per_unit:20  unit:MINUTE}  limit_remaining:15  duration_until_reset:{seconds:19}}  statuses:{code:OK  current_limit:{requests_per_unit:10  unit:HOUR}  limit_remaining:5  duration_until_reset:{seconds:619}}
            	            	actual:  overall_code:OK  statuses:{code:OK  current_limit:{requests_per_unit:20  unit:MINUTE}  limit_remaining:15  duration_until_reset:{seconds:20}}  statuses:{code:OK  current_limit:{requests_per_unit:10  unit:HOUR}  limit_remaining:5  duration_until_reset:{seconds:620}}
```

I will add the documentation tomorrow. Thanks!

2020-11-03 15:16 UTC, mattklein123 requested changes
LGTM with small comment, thanks.

/wait

2020-11-03 15:16 UTC, mattklein123 commented on README.md
> +To costum near_limit ratio threshold, you can specify with `NEAR_LIMIT_RATIO` environment variable. It defaults to `0.8` (0-1 scale). These are examples of generated stats for some configured rate li
```suggestion
To use a custom near_limit ratio threshold, you can specify with `NEAR_LIMIT_RATIO` environment variable. It defaults to `0.8` (0-1 scale). These are examples of generated stats for some configured rate limit rules from the above examples:
```

2020-11-03 20:27 UTC, mattklein123 approved these changes
Thanks!

2020-11-03 20:27 UTC, merged