181 include value in metrics for unspecified
envoyproxy/ratelimit pull request #389
Opened 2023-01-08 16:07 UTC by jespersoderlund

Add configuration key to a ratelimit descriptor to allow it to include the value in a statistics value.

2023-01-15 22:09 UTC, jespersoderlund commented
Renamed the config-parameter to "detailed_metric" instead of the crazy-long config parameter I used first

2023-01-17 16:37 UTC, mattklein123 requested changes
LGTM with small comment nit, thanks.

2023-01-17 16:37 UTC, mattklein123 commented on README.md
> +In this example there of where the extended metrics for a key where there will be detailed metrics even for the unknown values.
Typo? Can't parse.

2023-01-17 19:11 UTC, jespersoderlund commented on README.md
> +In this example there of where the extended metrics for a key where there will be detailed metrics even for the unknown values.
Yeah, not very clear, fixed

2023-01-17 20:42 UTC, mattklein123 approved these changes
Thanks!

2023-01-17 20:42 UTC, merged

2023-01-26 14:06 UTC, marinasalmen commented
Hey @mattklein123 I think something went wrong with the image build and push.
Could you maybe take a look at it? Looking forward for this feature! 🙌

2023-01-26 18:09 UTC, mattklein123 commented
This should be fixed. There was a credential issue.