Allow override of runtime app directory
envoyproxy/ratelimit pull request #397
Opened 2023-02-17 22:02 UTC by PeterL328

Allow override of runtime app directory

2023-02-21 23:06 UTC, PeterL328 commented
@mattklein123 Can I get an approval to run the workflow?

2023-02-22 20:19 UTC, PeterL328 commented
@ysawa0 Do you mind approving above workflow?

2023-02-24 23:17 UTC, mattklein123 requested changes
Please add docs for this in the README. Otherwise LGTM, thanks.

2023-03-01 03:25 UTC, PeterL328 commented
Thanks for review. Updated PR.

2023-03-02 15:52 UTC, mattklein123 approved these changes
Thanks!

2023-03-02 16:10 UTC, merged